services:
    sonata.admin.areaAtuacao:
        class: IFC\IfcBundle\Admin\AreaAtuacaoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Area atuacao" }
        arguments:
            - ~
            - IFC\IfcBundle\Entity\AreaAtuacao
            - ~
    sonata.admin.Contato:
        class: IFC\IfcBundle\Admin\ContatoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Contato" }
        arguments:
            - ~
            - IFC\IfcBundle\Entity\Contato
            - ~
    sonata.admin.curso:
        class: IFC\IfcBundle\Admin\CursoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Curso" }
        arguments:
            - ~
            - IFC\IfcBundle\Entity\Curso
            - ~
    sonata.admin.Empresa:
        class: IFC\IfcBundle\Admin\EmpresaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Empresa" }
        arguments:
            - ~
            - IFC\IfcBundle\Entity\Empresa
            - ~
    sonata.admin.endereco:
        class: IFC\IfcBundle\Admin\EnderecoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Endereco" }
        arguments:
            - ~
            - IFC\IfcBundle\Entity\Endereco
            - ~
    sonata.admin.estagiario:
        class: IFC\IfcBundle\Admin\EstagiarioAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Estagiario" }
        arguments:
            - ~
            - IFC\IfcBundle\Entity\Estagiario
            - ~
    sonata.admin.estagio:
        class: IFC\IfcBundle\Admin\EstagioAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Estagio" }
        arguments:
            - ~
            - IFC\IfcBundle\Entity\Estagio
            - ~

    sonata.admin.modalidade:
        class: IFC\IfcBundle\Admin\ModalidadeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Modalidade" }
        arguments:
            - ~
            - IFC\IfcBundle\Entity\Modalidade
            - ~


    sonata.admin.pessoa:
        class: IFC\IfcBundle\Admin\PessoaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Pessoa" }
        arguments:
            - ~
            - IFC\IfcBundle\Entity\Pessoa
            - ~
        calls:
            - [ setTranslationDomain, [AcmeDemoBundle]]
